### ISSUE TITLE
Is this working server?

### ISSUE THREAD

**Issue by lov3catch** [TheDemonLife/Lineage2-Server-Interlude#1]
Is this working server?

**Comment by VanitasQQ** [comment]
Yep

**Comment by lov3catch** [comment]
How to run client?

**Comment by VanitasQQ** [comment]
1. Upload the backup database via Navicat. (Create 2 databases [la2_login] and [la2_game] (watch more on youtube)
2. Write the password to the root user (from DataBase) in the configs of gameserver and LoginServer
2.1 For gameserver -> game/config/network/network.properties
2.2 For loginserver -> login/config/main/network.properties
3. Register GamerServer. Open file register_gameserver.bat (if windows) or register_gameserver.sh (if linux). Create a hexid file, and throw it in: ~ \ game\config\network
4. Launch LoginServer, and after launching LoginServer, launch GamerServer.
